ORIGINAL_VIDEO_URL = 'data/original.wav'
VOWEL_VIDEO_BASE_PATH = 'data/vowel'
CONSONANT_VIDEO_BASE_PATH = 'data/consonant'

VOWEL_FREQUENCY_HIGH_THRESHOLD = 2500
VOWEL_AMPLITUDE_LOW_THRESHOLD = 115
CONSONANT_AMPLITUDE_LOW_THRESHOLD = 110
VOICE_AMPLITUDE_LOW_THRESHOLD = 0.06
